transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_CoinRegBACKGTYPE.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_COINCOMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_upTRANSITIONCOUNTER.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_upLIFECOUNTER.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_STATEMACHINEGAME.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_LastRegBACKGTYPE.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_WINCOMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_MATRIXCOMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_LIFE_COMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_LastRegisterCOMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_FirstRegisterCOMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_STATEMACHINEBACKG.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_RegBACKGTYPE.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_STATEMACHINEPOINT.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_RegPOINTTYPE.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_upCOUNTER.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_SEVENSEG1.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_BIN2BCD1.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_upSPEEDCOUNTER.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_SPEEDCOMPARATOR.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/shift_reg_start_done.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/max7219_ctrl.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_DEBOUNCE1.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/BB_SYSTEM.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_upBLINKCOUNTER.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/SC_RegCOINTYPE.v}
vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/rtl {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/rtl/CC_SHIFT_COMPARATOR.v}

vlog -vlog01compat -work work +incdir+C:/Users/FELIX/Desktop/Universidad/Segundo\ semestre/Sistemas\ Electronicos\ Digitales/Proyecto\ 1/Final\ con\ Monedas/Final\ con\ Monedas/simulation/modelsim {C:/Users/FELIX/Desktop/Universidad/Segundo semestre/Sistemas Electronicos Digitales/Proyecto 1/Final con Monedas/Final con Monedas/simulation/modelsim/TB_SYSTEM.vt}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cycloneive_ver -L rtl_work -L work -voptargs="+acc"  TB_SYSTEM

add wave *
view structure
view signals
run -all
